# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enginecmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enginecmd.proto',
  package='encommand',
  syntax='proto3',
  serialized_options=_b('Z\014enbuffer/cmd'),
  serialized_pb=_b('\n\x0f\x65nginecmd.proto\x12\tencommand\">\n\x07\x43ommand\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0b\n\x03Opa\x18\x02 \x01(\x05\x12\x0b\n\x03Opb\x18\x03 \x01(\x05\x12\x0b\n\x03Opc\x18\x04 \x01(\x05\".\n\x0b\x43ommandList\x12\x1f\n\x03\x43md\x18\x01 \x03(\x0b\x32\x12.encommand.CommandB\x0eZ\x0c\x65nbuffer/cmdb\x06proto3')
)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='encommand.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='encommand.Command.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Opa', full_name='encommand.Command.Opa', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Opb', full_name='encommand.Command.Opb', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Opc', full_name='encommand.Command.Opc', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=92,
)


_COMMANDLIST = _descriptor.Descriptor(
  name='CommandList',
  full_name='encommand.CommandList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='encommand.CommandList.Cmd', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=140,
)

_COMMANDLIST.fields_by_name['Cmd'].message_type = _COMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['CommandList'] = _COMMANDLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'enginecmd_pb2'
  # @@protoc_insertion_point(class_scope:encommand.Command)
  ))
_sym_db.RegisterMessage(Command)

CommandList = _reflection.GeneratedProtocolMessageType('CommandList', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDLIST,
  __module__ = 'enginecmd_pb2'
  # @@protoc_insertion_point(class_scope:encommand.CommandList)
  ))
_sym_db.RegisterMessage(CommandList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
